# Github action configuration build and pack video library
# Author: Rahul Shukla <rahul.shukla@ilimi.in>


name: Sunbird-Video-Player

# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies 
      run: |
        (npm install)

    - name: Build video player library
      run: |
        (npm run build)

    - name: Package video player library 
      run: |
        (cd dist/video-player-v2 && npm pack)
    
    - name: Library artifact generation
      uses: actions/upload-artifact@v1
      with:
        name: Library generation
        path: dist/video-player-v2

      env:
        CI: true
        
